name: DMARC Check

on:
  schedule:
    - cron: "0 2 * * *"   # daily run
  workflow_dispatch:       # manual run

  push:
    paths:
      - "data/companies.json" 

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install dnspython

      - name: Run DMARC check
        run: python scripts/check_dmarc.py

      - name: Commit updated results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add public/non_dmarc.json

          git diff --cached --quiet || git commit -m "Update DMARC status"

          git push
